# Generated by Django 5.0.4 on 2024-05-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileShare_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
